/*:
 # LeetCode题库
 
 - [树](https://leetcode-cn.com/tag/tree/)
     - [0094. 二叉树的中序遍历](https://leetcode-cn.com/problems/binary-tree-inorder-traversal/)
     - [0100. 相同的树](https://leetcode-cn.com/problems/same-tree/)
     - [0101. 对称二叉树](https://leetcode-cn.com/problems/symmetric-tree/)
     - [0102. 二叉树的层序遍历](https://leetcode-cn.com/problems/binary-tree-level-order-traversal/)
     - [0104. 二叉树的最大深度](https://leetcode-cn.com/problems/maximum-depth-of-binary-tree/)
     - [0105. 从前序与中序遍历序列构造二叉树](https://leetcode-cn.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/)
     - [0106. 从中序与后序遍历序列构造二叉树](https://leetcode-cn.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/)
     - [0107. 二叉树的层序遍历 II](https://leetcode-cn.com/problems/binary-tree-level-order-traversal-ii/)
     - [0110. 平衡二叉树](https://leetcode-cn.com/problems/balanced-binary-tree/)
     - [0111. 二叉树的最小深度](https://leetcode-cn.com/problems/minimum-depth-of-binary-tree/)
     - [0114. 二叉树展开为链表](https://leetcode-cn.com/problems/flatten-binary-tree-to-linked-list/)
     - [0116. 填充每个节点的下一个右侧节点指针](https://leetcode-cn.com/problems/populating-next-right-pointers-in-each-node/)
     - [0117. 填充每个节点的下一个右侧节点指针 II](https://leetcode-cn.com/problems/populating-next-right-pointers-in-each-node-ii/)
     - [0124. 二叉树中的最大路径和](https://leetcode-cn.com/problems/binary-tree-maximum-path-sum/)
     - [0144. 二叉树的前序遍历](https://leetcode-cn.com/problems/binary-tree-preorder-traversal/)
     - [0145. 二叉树的后序遍历](https://leetcode-cn.com/problems/binary-tree-postorder-traversal/)
     - [0199. 二叉树的右视图](https://leetcode-cn.com/problems/binary-tree-right-side-view/)
     - [0222. 完全二叉树的节点个数](https://leetcode-cn.com/problems/count-complete-tree-nodes/)
     - [0226. 翻转二叉树](https://leetcode-cn.com/problems/invert-binary-tree/)
     - [0257. 二叉树的所有路径](https://leetcode-cn.com/problems/binary-tree-paths/)
     - [0429. N 叉树的层序遍历](https://leetcode-cn.com/problems/n-ary-tree-level-order-traversal/)
     - [0404. 左叶子之和](https://leetcode-cn.com/problems/sum-of-left-leaves/)
     - [0513. 找树左下角的值](https://leetcode-cn.com/problems/find-bottom-left-tree-value/)
     - [0515. 在每个树行中找最大值](https://leetcode-cn.com/problems/find-largest-value-in-each-tree-row/)
     - [0559. N 叉树的最大深度](https://leetcode-cn.com/problems/maximum-depth-of-n-ary-tree/)
     - [0572. 另一棵树的子树](https://leetcode-cn.com/problems/subtree-of-another-tree/)
     - [0589. N叉树的前序遍历](https://leetcode-cn.com/problems/n-ary-tree-preorder-traversal/)
     - [0590. N叉树的后序遍历](https://leetcode-cn.com/problems/n-ary-tree-postorder-traversal/)
     - [0637. 二叉树的层平均值](https://leetcode-cn.com/problems/average-of-levels-in-binary-tree/)
     - [0958. 二叉树的完全性检验](https://leetcode-cn.com/problems/check-completeness-of-a-binary-tree/)
 
 - [数组](https://leetcode-cn.com/tag/array/)
     - [0027. 移除元素](https://leetcode-cn.com/problems/remove-element/)
     - [0035. 搜索插入位置](https://leetcode-cn.com/problems/search-insert-position/)
     - [0059. 螺旋矩阵 II](https://leetcode-cn.com/problems/spiral-matrix-ii/)
     - [0209. 长度最小的子数组](https://leetcode-cn.com/problems/minimum-size-subarray-sum/)
     - [0704. 二分查找](https://leetcode-cn.com/problems/binary-search/)
     - [0977. 有序数组的平方](https://leetcode-cn.com/problems/squares-of-a-sorted-array/)
 - [链表](https://leetcode-cn.com/tag/linked-list/)
     - [0203. 移除链表元素](https://leetcode-cn.com/problems/remove-linked-list-elements/)
     - [0206. 反转链表](https://leetcode-cn.com/problems/reverse-linked-list/)
     - [0707. 设计链表](https://leetcode-cn.com/problems/design-linked-list/)
 - [字符串](https://leetcode-cn.com/tag/string/problemset/)
     - [0344. 反转字符串](https://leetcode-cn.com/problems/reverse-string)
     - [0541. 反转字符串](https://leetcode-cn.com/problems/reverse-string-ii/)
     - [151. 翻转字符串里的单词](https://leetcode-cn.com/problems/reverse-words-in-a-string/)
 */

/*:
 # 剑指Offer

 - [05. 替换空格](https://leetcode-cn.com/problems/ti-huan-kong-ge-lcof/)
 - [29. 顺时针打印矩阵](https://leetcode-cn.com/problems/shun-shi-zhen-da-yin-ju-zhen-lcof/)
 - [58 - II. 左旋转字符串](https://leetcode-cn.com/problems/zuo-xuan-zhuan-zi-fu-chuan-lcof/)
 */
